import { describe, expect, it } from "vitest";
import { serializeRobotsTxt } from "../src/infrastructure/robots/robots-writer";
import { serializeSitemapIndex } from "../src/infrastructure/xml/sitemap-index-writer";
import { createSitemapHeader } from "../src/infrastructure/xml/sitemap-writer";

describe("generated file signatures", () => {
  it("adds the mandatory signature to sitemap files", () => {
    const header = createSitemapHeader({
      generatedAt: "2026-05-29T00:00:00.000Z",
      sitemapName: "records",
      page: 1,
    });

    expect(header).toContain("<!-- Generated by NDT SEO Indexer -->");
    expect(header).toContain("<!-- Maintained by NDT Digital -->");
    expect(header).toContain("<!-- Generated at: 2026-05-29T00:00:00.000Z -->");
    expect(header).toContain("<!-- Sitemap: records -->");
    expect(header).toContain("<!-- Page: 1 -->");
  });

  it("adds the mandatory signature to sitemap index files", () => {
    const sitemapIndex = serializeSitemapIndex(
      "https://example.com",
      [
        {
          name: "static",
          filename: "sitemaps/static.xml",
          urlCount: 1,
          lastmod: "2026-05-29T00:00:00.000Z",
        },
      ],
      { generatedAt: "2026-05-29T00:00:00.000Z" },
    );

    expect(sitemapIndex).toContain("<!-- Generated by NDT SEO Indexer -->");
    expect(sitemapIndex).toContain("<!-- Maintained by NDT Digital -->");
    expect(sitemapIndex).toContain("<!-- Type: sitemap-index -->");
  });

  it("adds the mandatory signature to robots.txt", () => {
    const robots = serializeRobotsTxt({
      siteUrl: "https://example.com",
      sitemapIndexFilename: "sitemap.xml",
      generatedAt: "2026-05-29T00:00:00.000Z",
    });

    expect(robots).toContain("# Generated by NDT SEO Indexer");
    expect(robots).toContain("# Maintained by NDT Digital");
    expect(robots).toContain("# Generated at: 2026-05-29T00:00:00.000Z");
    expect(robots).toContain("Sitemap: https://example.com/sitemap.xml");
  });
});
