export type GeneratedFileSignatureInput = {
  generatedAt?: string;
  type?: string;
  sitemapName?: string;
  page?: number;
};

const GENERATOR_NAME = "NDT SEO Indexer";
const ORGANIZATION_NAME = "NDT Digital";

export function createXmlSignatureComment(
  input: GeneratedFileSignatureInput = {},
): string {
  const generatedAt = input.generatedAt ?? new Date().toISOString();
  const lines = [
    `<!-- Generated by ${GENERATOR_NAME} -->`,
    `<!-- Maintained by ${ORGANIZATION_NAME} -->`,
    `<!-- Generated at: ${generatedAt} -->`,
  ];

  if (input.type) {
    lines.push(`<!-- Type: ${input.type} -->`);
  }

  if (input.sitemapName) {
    lines.push(`<!-- Sitemap: ${input.sitemapName} -->`);
  }

  if (typeof input.page === "number") {
    lines.push(`<!-- Page: ${input.page} -->`);
  }

  return `${lines.join("\n")}\n`;
}

export function createTextSignatureComment(
  input: GeneratedFileSignatureInput = {},
): string {
  const generatedAt = input.generatedAt ?? new Date().toISOString();
  const lines = [
    `# Generated by ${GENERATOR_NAME}`,
    `# Maintained by ${ORGANIZATION_NAME}`,
    `# Generated at: ${generatedAt}`,
  ];

  if (input.type) {
    lines.push(`# Type: ${input.type}`);
  }

  return `${lines.join("\n")}\n`;
}
